name: maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn -U -B -DskipTests=false clean verify
      - name: Package
        run: mvn -B -DskipTests=false package
      - name: Upload fat JAR and launchers
        uses: actions/upload-artifact@v4
        with:
          name: smsd-jar-and-launchers
          path: |
            target/*-jar-with-dependencies.jar
            target/bin/

